run:
  REACT_APP_API_BASE_URL=http://localhost:8000 yarn start

build:
  yarn build

deploy:
  rsync -Prv -e "ssh -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -F /dev/null" ./dist/* debian@ameo.dev:/var/www/spotifytrack.net/
