build-wasm-client:
  cd src/musicGalaxy/WasmClient/wasm_engine && just build

run:
  just build-wasm-client
  REACT_APP_API_BASE_URL=http://localhost:8000 REACT_APP_SITE_URL=http://localhost:9000 yarn start --host 0.0.0.0

build:
  just build-wasm-client
  yarn build
  just monkey-patch-worker-url

deploy:
  rsync -Prv -e "ssh -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -F /dev/null" ./dist/* debian@ameo.dev:/var/www/spotifytrack.net/

monkey-patch-worker-url:
  # Loading web workers from different origins is not supported, so this re-writes the worker URL to load it directly from the same origin.
  sed -i --regexp-extended "s/new URL\(\\w+\.\\w+/new URL\('https:\/\/spotifytrack\.net\/'/g" ./dist/musicGalaxy*.js
