build-wasm-client:
  cd src/artistAverager/ArtistMap/WasmClient/wasm_engine && just build

run:
  just build-wasm-client
  REACT_APP_API_BASE_URL=http://localhost:8000 REACT_APP_SITE_URL=http://localhost:9000 yarn start --host 0.0.0.0

build:
  just build-wasm-client
  yarn build

deploy:
  rsync -Prv -e "ssh -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -F /dev/null" ./dist/* debian@ameo.dev:/var/www/spotifytrack.net/
