set dotenv-load := true

docker-build:
  docker build -t ${DOCKER_IMAGE}:latest .

spawn-redis:
  docker kill redis || true
  docker rm redis || true
  docker run --rm -d -p 6379:6379 --name redis redis

docker-start:
  docker rm spotifytrack-server || true
  docker run -it --net host -p 3999:3999 --name spotifytrack-server \
    -e ROCKET_DATABASES="{ spotify_homepage = { url = \"$DATABASE_URL\" } }" \
    -e PORT="$PORT" \
    -e SPOTIFY_CLIENT_ID="$SPOTIFY_CLIENT_ID" \
    -e SPOTIFY_CLIENT_SECRET="$SPOTIFY_CLIENT_SECRET" \
    -e API_SERVER_URL="$API_SERVER_URL" \
    -e WEBSITE_URL="$WEBSITE_URL" \
    -e REDIS_URL="$REDIS_URL" \
    -e ADMIN_API_TOKEN="$ADMIN_API_TOKEN" \
    ${DOCKER_IMAGE}:latest

run:
  RUST_LOG=info ROCKET_LOG=info RUST_BACKTRACE=1 RUSTFLAGS="--cfg tokio_unstable --cfg foundations_unstable" cargo run

build-and-deploy:
  #!/bin/bash

  just docker-build
  docker save $DOCKER_IMAGE:latest | bzip2 > /tmp/spotifytrack-server.tar.bz2
  scp /tmp/spotifytrack-server.tar.bz2 debian@ameo.dev:/tmp/spotifytrack-server.tar.bz2
  ssh debian@ameo.dev -t "cat /tmp/spotifytrack-server.tar.bz2 | bunzip2 | docker load && docker kill spotifytrack-server && docker container rm spotifytrack-server && docker run -d --name spotifytrack-server --net host --restart always -e ROCKET_DATABASES='{ spotify_homepage = { url = \"$DATABASE_URL\" } }' -e PORT=4100 -e SPOTIFY_CLIENT_ID='$SPOTIFY_CLIENT_ID' -e SPOTIFY_CLIENT_SECRET='$SPOTIFY_CLIENT_SECRET' -e API_SERVER_URL='https://spotifytrack.net/api' -e WEBSITE_URL='https://spotifytrack.net' -e REDIS_URL='$REDIS_URL' -e TELEMETRY_SERVER_PORT=4103 -e ADMIN_API_TOKEN='$ADMIN_API_TOKEN' -e RUST_LOG=info -e ROCKET_LOG=info -e ROCKET_LOG_level=normal $DOCKER_IMAGE:latest && rm /tmp/spotifytrack-server.tar.bz2" && rm /tmp/spotifytrack-server.tar.bz2
