docker_build:
  docker build -t ameo/spotify-homepage-backend .

spawn_redis:
  docker kill redis || true
  docker rm redis || true
  docker run --rm -d -p 6379:6379 --name redis redis

docker_start:
  docker rm spotifytrack-server || true
  echo "$SPOTIFY_CLIENT_ID"
  docker run -it --net host -p 3999:3999 -e ROCKET_DATABASES="{ spotify_homepage = { url = \"$DATABASE_URL\" } }" -e PORT="$PORT" -e SPOTIFY_CLIENT_ID="$SPOTIFY_CLIENT_ID" -e SPOTIFY_CLIENT_SECRET="$SPOTIFY_CLIENT_SECRET" -e SERVER_BASE_URL="$SERVER_BASE_URL" -e REDIS_URL="$REDIS_URL" -e ADMIN_API_TOKEN="$ADMIN_API_TOKEN" --name spotifytrack-server ameo/spotify-homepage-backend
