docker_build:
  docker build -t ameo/spotify-homepage-backend .

spawn_redis:
  docker kill redis || true
  docker rm redis || true
  docker run --rm -d -p 6379:6379 --name redis redis

docker_start:
  export $(egrep -v '^#' .env | xargs)
  docker run -it --net host -p 3999:3999 -e ROCKET_DATABASES="{ spotify_homepage = { url = \"$DATABASE_URL\" } }" -e "ROCKET_PORT=3999" -e SPOTIFY_CLIENT_ID="$SPOTIFY_CLIENT_ID" -e SPOTIFY_CLIENT_SECRET="$SPOTIFY_CLIENT_SECRET" -e SERVER_BASE_URL="$SERVER_BASE_URL" -e REDIS_URL="$REDIS_URL" --name spotifytrack-server ameo/spotify-homepage-backend
