export const BASE_ARTIST_COLOR = 0x1fcf36;
export const BASE_CONNECTION_COLOR = 0x2288ee;

export const MOVEMENT_SPEED_UNITS_PER_SECOND = 48;

export const ARTIST_LABEL_TEXT_SIZE = 144.8;
export const ARTIST_GEOMETRY_SIZE = 1.7;
